### ISSUE TITLE
Put the condition for Overweight

### ISSUE THREAD

**Issue by dscgecbsp** [dscgecbsp/BMI-Calculator-HacktoberFest-2022#1]

**Comment by Aksbj** [comment]
Hello Sir, Can you assighn this issue to me

**Comment by dscgecbsp** [comment]
I assighn this issue to you @Aksbj

**Comment by dscgecbsp** [comment]
i assighn this issue to you @Deeptan2002

**Comment by mohnishjamde** [comment]
please assign this problem to me.

**Comment by swikrit92** [comment]
please assign this issue to me @dscgecbsp

**Comment by Vikas-sr001** [comment]
pls assign this issue to me @dscgecbsp

**Comment by MuskanVerma11** [comment]
Please assign this issue to me @dscgecbsp

**Comment by Sparsh0211** [comment]
Please assign this issue to me @dscgecbsp

**Comment by kunalsahuu** [comment]
can you please assign this issue to me @dscgecbsp

**Comment by Yashwant711** [comment]
Please assign this issue to me @dscgecbsp
